version: "3"

services:
  service:
    container_name: kafka-service
    build: .
    command: /main -s kafka-s:9092
    ports:
      - 2000:2000
    depends_on:
      - kafka
  kafka:
    container_name: kafka-s
    image: 'bitnami/kafka:latest'
    ports:
      - :9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - :2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

